**Import Essential Packages**

In [2]:
import numpy as np
import pandas as pd

## Answer_Q1

In [ ]:
np.nonzero([6,0,7,0,4,0])

(array([0, 2, 4]),)

## Answer_Q2

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


## Answer_Q3

In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


[[ 0.49250201 -0.85529952 -0.41736451 -0.01081895  0.57989033]
 [ 1.19615496 -1.2830786   0.66370822  0.07875351  0.1249409 ]
 [ 1.14161411  0.91130948  0.31330909  1.19384882  0.26009479]
 [ 0.9403001  -0.85121778 -1.81224089  1.10550002 -2.05965606]
 [-1.17776054  0.52085134  1.13023468 -1.62645223 -0.55912329]]


## Answer_Q4

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)


[0.14433989 0.22178901 0.29291969 0.63450832 0.65295372 0.73376846
 0.75873344 0.82146843 0.84054216 0.92336023]


## Answer_Q5

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.163637117973


In [ ]:
X

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
Y

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])

In [ ]:
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

## Answer_Q6

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')
df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

## Answer_Q7

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv')
df

Team  Goals  Shots on target  Shots off target  \
0               Croatia      4               13                12   
1        Czech Republic      4               13                18   
2               Denmark      4               10                10   
3               England      5               11                18   
4                France      3               22                24   
5               Germany     10               32                32   
6                Greece      5                8                18   
7                 Italy      6               34                45   
8           Netherlands      2               12                36   
9                Poland      2               15                23   
10             Portugal      6               22                42   
11  Republic of Ireland      1                7                12   
12               Russia      5                9                31   
13                Spain     12               42                33   
14               Sweden      5               17                19   
15              Ukraine      2                7                26   

   Shooting Accuracy % Goals-to-shots  Total shots (inc. Blocked)  \
0              51.9%            16.0%                          32   
1              41.9%            12.9%                          39   
2              50.0%            20.0%                          27   
3              50.0%            17.2%                          40   
4              37.9%             6.5%                          65   
5              47.8%            15.6%                          80   
6              30.7%            19.2%                          32   
7              43.0%             7.5%                         110   
8              25.0%             4.1%                          60   
9              39.4%             5.2%                          48   
10             34.3%             9.3%                          82   
11             36.8%             5.2%                          28   
12             22.5%            12.5%                          59   
13             55.9%            16.0%                         100   
14             47.2%            13.8%                          39   
15             21.2%             6.0%                          38   

    Hit Woodwork  Penalty goals  Penalties not scored  ...  Saves made  \
0              0              0                     0  ...          13   
1              0              0                     0  ...           9   
2              1              0                     0  ...          10   
3              0              0                     0  ...          22   
4              1              0                     0  ...           6   
5              2              1                     0  ...          10   
6              1              1                     1  ...          13   
7              2              0                     0  ...          20   
8              2              0                     0  ...          12   
9              0              0                     0  ...           6   
10             6              0                     0  ...          10   
11             0              0                     0  ...          17   
12             2              0                     0  ...          10   
13             0              1                     0  ...          15   
14             3              0                     0  ...           8   
15             0              0                     0  ...          13   

    Saves-to-shots ratio  Fouls Won Fouls Conceded  Offsides  Yellow Cards  \
0                  81.3%         41             62         2             9   
1                  60.1%         53             73         8             7   
2                  66.7%         25             38         8             4   
3                  88.1%         43             45         6             5   
4                  54.

In [ ]:
df[df['Team'].str.contains('G')]

Team  Goals  Shots on target  Shots off target Shooting Accuracy  \
5  Germany     10               32                32             47.8%   
6   Greece      5                8                18             30.7%   

  % Goals-to-shots  Total shots (inc. Blocked)  Hit Woodwork  Penalty goals  \
5            15.6%                          80             2              1   
6            19.2%                          32             1              1   

   Penalties not scored  ...  Saves made  Saves-to-shots ratio  Fouls Won  \
5                     0  ...          10                 62.6%         63   
6                     1  ...          13                 65.1%         67   

  Fouls Conceded  Offsides  Yellow Cards  Red Cards  Subs on  Subs off  \
5             49        12             4          0       15        15   
6             48        12             9          1       12        12   

   Players Used  
5            17  
6            20  

[2 rows x 35 columns]

## Answer_Q8

In [ ]:
df[(df['Goals']>4) & (df['Clean Sheets']>=1)]

Team  Goals  Shots on target  Shots off target Shooting Accuracy  \
3    England      5               11                18             50.0%   
5    Germany     10               32                32             47.8%   
6     Greece      5                8                18             30.7%   
7      Italy      6               34                45             43.0%   
10  Portugal      6               22                42             34.3%   
13     Spain     12               42                33             55.9%   
14    Sweden      5               17                19             47.2%   

   % Goals-to-shots  Total shots (inc. Blocked)  Hit Woodwork  Penalty goals  \
3             17.2%                          40             0              0   
5             15.6%                          80             2              1   
6             19.2%                          32             1              1   
7              7.5%                         110             2              0   
10             9.3%                          82             6              0   
13            16.0%                         100             0              1   
14            13.8%                          39             3              0   

    Penalties not scored  ...  Saves made  Saves-to-shots ratio  Fouls Won  \
3                      0  ...          22                 88.1%         43   
5                      0  ...          10                 62.6%         63   
6                      1  ...          13                 65.1%         67   
7                      0  ...          20                 74.1%        101   
10                     0  ...          10                 71.5%         73   
13                     0  ...          15                 93.8%        102   
14                     0  ...           8                 61.6%         35   

   Fouls Conceded  Offsides  Yellow Cards  Red Cards  Subs on  Subs off  \
3              45         6             5          0       11        11   
5              49        12             4          0       15        15   
6              48        12             9          1       12        12   
7              89        16            16          0       18        18   
10             90        10            12          0       14        14   
13             83        19            11          0       17        17   
14             51         7             7          0        9         9   

    Players Used  
3             16  
5             17  
6             20  
7             19  
10            16  
13            18  
14            18  

[7 rows x 35 columns]

## Answer_Q9

In [ ]:
filtered_df = df[(df['Yellow Cards'] < 6) | (df['Red Cards'] == 1)]
for team in filtered_df['Team']:
    print(team)

Denmark
England
Germany
Greece
Netherlands
Poland
Republic of Ireland
Ukraine


## Answer_Q10

In [4]:
df1=pd.DataFrame({'Team': ['England','Greece','Portugal','Sweden'],'Ranking':[9,14,7,12]})
df1

Team  Ranking
0   England        9
1    Greece       14
2  Portugal        7
3    Sweden       12

In [7]:
pd.merge(df,df1,on='Team',how='right')

Team  Goals  Shots on target  Shots off target Shooting Accuracy  \
0   England      5               11                18             50.0%   
1    Greece      5                8                18             30.7%   
2  Portugal      6               22                42             34.3%   
3    Sweden      5               17                19             47.2%   

  % Goals-to-shots  Total shots (inc. Blocked)  Hit Woodwork  Penalty goals  \
0            17.2%                          40             0              0   
1            19.2%                          32             1              1   
2             9.3%                          82             6              0   
3            13.8%                          39             3              0   

   Penalties not scored  ...  Saves-to-shots ratio  Fouls Won  Fouls Conceded  \
0                     0  ...                 88.1%         43              45   
1                     1  ...                 65.1%         67              48   
2                     0  ...                 71.5%         73              90   
3                     0  ...                 61.6%         35              51   

  Offsides  Yellow Cards  Red Cards  Subs on  Subs off  Players Used  Ranking  
0        6             5          0       11        11            16        9  
1       12             9          1       12        12            20       14  
2       10            12          0       14        14            16        7  
3        7             7          0        9         9            18       12  

[4 rows x 36 columns]